### ISSUE TITLE
sync workflow should poll instead of being triggered only with pushes

### ISSUE THREAD

**Issue by Zethson** [qbicsoftware/qube-cli#170]
**Is your feature request related to a problem? Please describe.**
An organization with many repositories would need to manually push something to all repository to trigger the sync workflow.

**Describe the solution you'd like**

Something like this: (Think this is every 10 minutes? I have to check that)
```
on:
  schedule:
    - cron:  '0 10 * * *'
```

Once a day should suffice?
The check is super quick and doesn't really reserve many resources.

https://github.com/qbicsoftware/qube-cli/blob/master/qube/create/templates/common_files/%7B%7B%20cookiecutter.commonName%20%7D%7D/.github/workflows/sync_project.yml

**Comment by Zethson** [comment]
Actually, the schedule should likely look more like this:

`0 1 * * *`

-> Then it would get triggered at 1 AM every day.

**Comment by sven1103** [comment]
👍
