### ISSUE TITLE
Console output does not break lines

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/qube-cli#201]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11536497/95344183-a713d980-08b9-11eb-9e0e-5c2de98fb9cd.png)

The console output does not wrap lines. This is a problem when using GitHub Actions since the default console width is not sufficient to display the error messages.

**To Reproduce**

1. run `qube lint` anywhere

**Expected behavior**

The console output does break lines if it is wider than the console (compare default linux/mac command line)

**System [please complete the following information]:**

everywhere

**Comment by Zethson** [comment]
https://rich.readthedocs.io/en/latest/console.html#overflow

Need to replace ellipsis formatting with fold

**Comment by Zethson** [comment]
And have to remove `no_wrap=True`

**Comment by Zethson** [comment]
Before:

![image](https://user-images.githubusercontent.com/21954664/96228883-75c09b00-0f96-11eb-93df-d9918f879fa6.png)

After:

![image](https://user-images.githubusercontent.com/21954664/96228981-9be63b00-0f96-11eb-9c80-96f1986fc55e.png)

**Comment by KochTobi** [comment]
Thanks a lot for fixing this so fast @Zethson !
